'use client';

import { useState } from 'react';

type Stop = { name: string; korean: string; note: string; booking?: string };
type Day = { date: string; day: string; theme: string; description: string; stops: Stop[]; must?: string };

const days: Day[] = [
  { date: 'Aug 25', day: 'Tue · Silka', theme: 'Arrival & recovery', description: 'Airport, bags, a nearby meal, nap and early night.', stops: [{ name: 'Home base', korean: '서울 종로구 창덕궁길 59-2', note: 'Jongno / Changdeokgung-gil' }] },
  { date: 'Aug 26', day: 'Wed · Silka', theme: 'Nails & designer second-hand', description: 'Keep it gentle: nails in Myeongdong, then Apgujeong resale browsing.', stops: [{ name: 'Gugus Apgujeong', korean: '서울 강남구 선릉로 846 구구스 압구정점', note: 'Pre-owned luxury' }, { name: 'Mihou’s Nail', korean: '서울 중구 명동', note: 'Message +82 10-5779-0737 on WhatsApp first' }], must: 'Arrange Mihou’s Nail if you want it.' },
  { date: 'Aug 27', day: 'Thu · Silka', theme: 'Work day', description: 'A quiet reading/work block, then a small local meal.', stops: [{ name: 'Hyundai Card Art Library', korean: '서울 용산구 이태원로 248 현대카드 아트 라이브러리', note: 'Bring photo ID and DIVE app' }, { name: 'Cafe Onion Anguk', korean: '서울 종로구 계동길 5 카페 어니언 안국점', note: 'Near home fallback' }] },
  { date: 'Aug 28', day: 'Fri · Silka', theme: 'Work & archive shopping', description: 'Morning work, then a light browse before Teresa arrives.', stops: [{ name: 'VASS Archive / Vintage', korean: '서울 마포구 독막로15길 3-18 1층 베이스', note: 'Check Instagram for current curation' }] },
  { date: 'Aug 29', day: 'Sat · together', theme: 'Arrival & Gyeongbokgung', description: 'Teresa arrives; keep the first afternoon beautiful but flexible.', stops: [{ name: 'Gyeongbokgung Palace', korean: '서울 종로구 사직로 161 경복궁', note: 'Aim to arrive 16:15–16:45; last entry 17:30' }, { name: 'ANAM', korean: '서울 종로구 계동길 37 안암', note: 'Welcome dinner option' }], must: 'If arrival runs late, skip the palace and wander Bukchon instead.' },
  { date: 'Aug 30', day: 'Sun · together', theme: 'Seongsu: design & fashion', description: 'A full, loose day of concept spaces, gallery, fashion and tea.', stops: [{ name: 'Foreplan', korean: '서울 성동구 왕십리로14길 30-11 포플랜', note: 'Coffee / brunch' }, { name: '032c Gallery Seoul', korean: '서울 성동구 성수이로10길 14 032c 갤러리 서울', note: 'Gallery' }, { name: 'HAUS NOWHERE + NUDAKE Tea House', korean: '서울 성동구 뚝섬로 433 하우스 노웨어 서울', note: 'Tea House is on 5F' }] },
  { date: 'Aug 31', day: 'Mon · together', theme: 'Yeonnam & Hongdae', description: 'A softer neighbourhood day: coffee, park, shops and dinner.', stops: [{ name: 'Coffee Nap Roasters', korean: '서울 마포구 성미산로27길 70 커피냅로스터스', note: 'Coffee' }, { name: 'Hangong-Gan', korean: '서울 마포구 연남동 561-4 한공간', note: 'Dinner; message them first' }] },
  { date: 'Sep 1', day: 'Tue · together', theme: 'Hannam: art, fashion & dinner', description: 'A considered museum and fashion day, ending with your nicest dinner.', stops: [{ name: 'Leeum Museum of Art', korean: '서울 용산구 이태원로55길 60-16 리움미술관', note: 'Architecture + exhibition' }, { name: 'SAN SAN GEAR Hannam', korean: '서울 용산구 이태원로55길 37-10 산산기어 한남', note: 'New DAIKEI MILLS-designed flagship' }, { name: 'Gongi', korean: '서울 용산구 이태원로45길 4 공기', note: 'Dinner' }], must: 'Book Leeum and Gongi.' },
  { date: 'Sep 2', day: 'Wed · together', theme: 'Museum SAN, Wonju', description: 'The full-day architecture pilgrimage: Tadao Ando, landscape, James Turrell, Meditation Hall and Antony Gormley.', stops: [{ name: 'Museum SAN', korean: '강원특별자치도 원주시 지정면 오크밸리2길 260 뮤지엄산', note: 'Leave Seoul early; keep evening open' }], must: 'Buy the Signature Pass if available.' },
  { date: 'Sep 3', day: 'Thu · together', theme: 'Audeum & Frieze', description: 'Early sound-and-architecture museum, then optional art fair afternoon.', stops: [{ name: 'Audeum Audio Museum', korean: '서울 서초구 신원동 560 오디움', note: 'Kengo Kuma; ticket required', booking: 'https://audeum.org/booking' }, { name: 'COEX / Frieze Seoul', korean: '서울 강남구 영동대로 513 코엑스', note: 'General entry from 15:00' }], must: 'Audeum first; Frieze only if the day still feels generous.' },
  { date: 'Sep 4', day: 'Fri · together', theme: 'Samcheong & Bukchon', description: 'Serious art, independent galleries and the Es Devlin installation.', stops: [{ name: 'MMCA Seoul', korean: '서울 종로구 삼청로 30 국립현대미술관 서울', note: 'Do Ho Suh + conceptual art' }, { name: 'FUTURA SEOUL', korean: '서울 종로구 북촌로 61 푸투라서울', note: 'Es Devlin: Come Home Again', booking: 'https://www.futuraseoul.org/57' }] },
  { date: 'Sep 5', day: 'Sat · together', theme: 'Slow Jongno + fireworks', description: 'Keep the day light, rest in the afternoon, then go early to Nodeul Island.', stops: [{ name: 'Nodeul Island Orange Play Zone', korean: '서울 용산구 노들섬', note: 'Fireworks; wristband exchange closes 17:00', booking: 'https://www.hanwhafireworks.com/' }], must: 'Book Orange Play Zone tickets if still available.' },
  { date: 'Sep 6', day: 'Sun · departure', theme: 'Airport day', description: 'Pack, breakfast nearby and leave from Seoul Station around 15:20–15:30.', stops: [{ name: 'Incheon Terminal 1', korean: '인천국제공항 제1여객터미널', note: 'Teresa' }, { name: 'Incheon Terminal 2', korean: '인천국제공항 제2여객터미널', note: 'Silka' }] },
];

function naver(query: string) { return `https://map.naver.com/p/search/${encodeURIComponent(query)}`; }
function kakao(query: string) { return `https://map.kakao.com/link/search/${encodeURIComponent(query)}`; }

export default function Home() {
  const [active, setActive] = useState('All');
  const shown = active === 'All' ? days : days.filter((d) => d.day.includes(active));
  return <main>
    <section className="hero"><p className="eyebrow">Seoul · Wonju · 25 Aug — 6 Sep 2026</p><h1>Silka & Teresa<br /><em>in Korea</em></h1><p className="lede">A living, clickable itinerary for design, art, architecture, fashion and long pauses.</p><p className="priority">Priority order: architecture, art, design and fashion. Cafés are optional.</p><div className="hero-actions"><a href="#itinerary">Open itinerary ↓</a><a className="quiet" href="https://map.naver.com/" target="_blank">Open Naver Map ↗</a></div></section>
    <nav className="filters" aria-label="Filter itinerary"><button className={active === 'All' ? 'selected' : ''} onClick={() => setActive('All')}>All days</button><button className={active === 'Silka' ? 'selected' : ''} onClick={() => setActive('Silka')}>Silka solo</button><button className={active === 'together' ? 'selected' : ''} onClick={() => setActive('together')}>Together</button></nav>
    <section id="itinerary" className="itinerary"><div className="section-head"><p className="eyebrow">The plan</p><h2>One beautiful district at a time.</h2><p>Tap a map button on your phone; it opens the location in your chosen Korean navigation service.</p></div>{shown.map((day) => <article className="day-card" key={day.date + day.day}><header><div><p className="date">{day.date}</p><p className="day">{day.day}</p></div><h3>{day.theme}</h3></header><p className="description">{day.description}</p>{day.must && <p className="must"><span>Book / note</span>{day.must}</p>}<div className="stops">{day.stops.map((stop) => <div className="stop" key={stop.name}><div><h4>{stop.name}</h4><p>{stop.note}</p><code>{stop.korean}</code>{stop.booking && <a className="booking" href={stop.booking} target="_blank">Booking / official site ↗</a>}</div><div className="map-actions"><a href={naver(stop.korean)} target="_blank">Naver Map ↗</a><a href={kakao(stop.korean)} target="_blank">KakaoMap ↗</a></div></div>)}</div></article>)}</section>
    <section className="need"><p className="eyebrow">Before leaving</p><h2>Book or download now</h2><ol><li><a href="https://audeum.org/booking" target="_blank">Audeum</a> · Sep 3</li><li><a href="https://ticket.leeum.org/leeum/personal/exhibitList.do" target="_blank">Leeum</a> and Gongi · Sep 1</li><li><a href="https://www.museumsan.org/eng/guidance/view_guide.jsp?m=5&s=2" target="_blank">Museum SAN Signature Pass</a> · Sep 2</li><li><a href="https://www.hanwhafireworks.com/" target="_blank">Orange Play Zone</a> · Sep 5</li><li><a href="https://apps.apple.com/us/app/hyundai-card-dive/id1469507774" target="_blank">Hyundai Card DIVE</a> · for Art Library entry</li></ol></section>
    <footer>Made for the trip · Keep this link pinned in Messages.</footer>
  </main>;
}
